### PR TITLE
Take user input

### PR DESCRIPTION
**Pull request by jithin-renji**
Although this is meant to be a `module`, many people would prefer to
run the program directly. So, I have added the functionality to ask
the user for a valid chemical structure.

I have also added a `help` command to get usage information.

TODO: Maybe add more examples to the help() function?

### CODE REVIEW

**Comment by jithin-renji** [comment]
The string holds the inputted compound structure. Since the only other 'command' is `help`, the naming seems fine.

**Comment by harshil21** [comment]
Thanks for contributing towards this!


> Although this is meant to be a `module`, many people would prefer to
> run the program directly. So, I have added the functionality to ask
> the user for a valid chemical structure.

Agreed. People might want to directly use the program instead.

> I have also added a `help` command to get usage information.

Instead of using `/help`, python has a built-in function `help()` which prints the docstrings of a class and/or its methods. I'll move the `/help` message into the class itself so it's clear for the users.

> TODO: Maybe add more examples to the help() function?

There's a branch which I'm working on which has a separate `examples.py` for examples. I'll also eventually add those to a folder `tests` to verify that it works.

**Comment by jithin-renji** [comment]
Great!

I have moved the output of `help()` into the class itself as a docstring. I had tried using Python's builtin `help()` function, but it is too detailed for a usage message. I have used `Namer.__doc__` instead.

**Comment by harshil21** [comment]
Perfect! That works too.

**Pull request merged**
